USE excite_study;

SET CHARACTER_SET_CLIENT = utf8mb4;
SET CHARACTER_SET_CONNECTION = utf8mb4;

-- 従業員テーブル
CREATE TABLE `TRN_EMPLOYEES` (
  `ID` INT unsigned NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_NUMBER` CHAR(6) NOT null COMMENT '社員番号',
  `MAIL_ADDRESS` VARCHAR(256) NOT NULL COMMENT 'メールアドレス',
  `FAMILY_NAME` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '苗字',
  `MIDDLE_NAME` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'ミドルネーム',
  `GIVEN_NAME` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '名前',
  `FAMILY_NAME_KANA` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '苗字（カナ）',
  `GIVEN_NAME_KANA` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '名前（カナ）',
  `MIDDLE_NAME_KANA` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'ミドルネーム（カナ）',
  `BIRTHDATE` DATE COMMENT '生年月日',
  `JOINING_DATE` DATE COMMENT '入社日',
  `RETIREMENT_DATE` DATE COMMENT '退職日',
  -- 
  `CREATE_USER` VARCHAR(256),
  `CREATE_TIMESTAMP` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(6),
  `UPDATE_USER` VARCHAR(256),
  `UPDATE_TIMESTAMP` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6),
  -- 
  PRIMARY KEY (`ID`)
);

-- 役職マスタ
CREATE TABLE `MST_POSITIONS` (
  `ID` INT(2) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `DISPLAY_ORDER` INT(2) unsigned,
  -- 
  `CREATE_USER` VARCHAR(256),
  `CREATE_TIMESTAMP` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(6),
  -- 
  PRIMARY KEY (`ID`)
);

-- 従業員-役職紐付けテーブル
CREATE TABLE `TRN_EMPLOYEE_POSITIONS` (
  `EMPLOYEE_ID` INT unsigned,
  `POSITION_ID` INT(2) unsigned,
  -- 
  `CREATE_USER` VARCHAR(256),
  `CREATE_TIMESTAMP` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(6),
  `UPDATE_USER` VARCHAR(256),
  `UPDATE_TIMESTAMP` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6),
  -- 
  PRIMARY KEY (`EMPLOYEE_ID`,`POSITION_ID`)
);

